### ISSUE TITLE
dos/win keeping env state

### ISSUE THREAD

**Issue by wluker** [jeapostrophe/dos#2]
dos is a very interesting approach, but I'm struggling with something seemingly basic.

If I run the following using dos/win
```
#lang racket
(require dos/win)
(define w0 (win-boot (win-env-replace (win-mbr) 'key0 '(val0))))
(displayln (win-env-read1 w0 'key0 #f))
```
I would expect 'key0 to be available within the w0 env, but it is not. Is this potentially a bug, or is this not how win-boot should be used?

Thanks for sharing this library.

**Comment by jeapostrophe** [comment]
Your example does not include any processes, and so one cycle of execution does not result in any writes to the environment. The environment is NOT persistent across cycles. `dos/win` is based on `dos/os2` where the zero element is just an empty hash map, which is what is getting returned as `w0`.

Compare:

```
#lang racket/base
(require dos/win dos/os2)

(define (try include-p?)
  (printf "try w/ ~a\n" include-p?)
  (define (proc0 x)
    (if #f ;; XXX There was an error in the library that requires this
           ;; to be #t
      (os2-exit x)
      x))
  (define ps (if include-p? (list proc0) (list)))
  (define w0 (win-env-replace (apply win-mbr ps) 'key0 '(val0)))
  (define w1 (win-boot w0))
  (displayln (win-env-read1 w0 'key0 #f))
  (displayln (win-env-read1 w1 'key0 #f))
  (printf "\n"))

(try #t)
(try #f)
```

**Comment by wluker** [comment]
> The environment is NOT persistent across cycles.

That was the flaw in my thinking. I was assuming the environment was meant to be persistent across cycles. Thanks for clearing that up. This make sense when I look at `examples/win.rkt`; you wouldn't want the `'gfx` effects to persist indefinitely.

I was playing around with managing a gui with `dos/win` where events would trigger a new cycle and for that I want the environment to be persistent across cycles. I was able to hack together a working prototype using `dos/win`, but I don't think that was the right approach. I like your domain-specific-operating-system ideas, so at this point I'm thinking I should make a `dos/gui` based on ideas from `dos/win`. This is interesting stuff. Thanks!
